name: Jobs on Pull Request
on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, synchronize, opened, reopened]
jobs:
  try-secret:
    runs-on: ubuntu-latest
    env:
      MY_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
    steps:
      - name: Print secret
        run: echo "Secret message is $MY_MESSAGE"

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup-action
      - name: Run lint job
        run: ./ci/lint_job.sh
  automation-tests:
    if: github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'test')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup-action
      - name: print url
        run: echo "BASE_URL=${{ vars.BASE_URL }}"
      - name: Create .env file
        run: echo "BASE_URL=${{ vars.BASE_URL }}" > .env
      - name: Print BASE_URL from .env
        run: cat .env
      - name: Run Playwright tests
        run: ./ci/playwright_job.sh
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
