name: Jobs on Pull Request
on:
  push:
    branches:
      - develop
  pull_request:
    types: [labeled, synchronize, opened, reopened]
jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup-action
      - name: Make lint script executable
        run: chmod +x ci/lint_job.sh
      - name: Run lint job
        run: ./ci/lint_job.sh
  automation-tests:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    # if: ${{ github.event.label.name == 'test' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/setup-action
      - name: Make lint script executable
        run: chmod +x ci/playwright_job.sh
      - name: Run Playwright tests
        run: ./ci/playwright_job.sh
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
