name: Jobs on Pull Request
on:
  push:
    branches:
      - develop
  pull_request:
    types: [labeled, opened, reopened, synchronize]
jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: .github/setup/action.yml
      - run: ./ci/lint_job.sh
  automation-tests:
    if: ${{ github.event.label.name == 'test' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: ./github/actions
      - name: Run Playwright tests
        run: ./ci/playwright_job.sh
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
