name: Jobs on Pull Request
on:
  pull_request:
    types: [labeled]
jobs:
  lint:
    if: ${{ github.event.label.name == 'cicd' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install lint
        run: npm install --save-dev eslint @eslint/js typescript typescript-eslint
      - name: Lint code
        run: npm run lint

  automation-tests:
    if: ${{ github.event.label.name == 'cicd' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npm run build
      - name: Run Playwright tests
        run: npm start
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
